name: Build UDP Proxy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Compile UDP Proxy
        run: x86_64-w64-mingw32-gcc -o udpproxy.exe udpproxy.c -lws2_32

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: udpproxy
          path: udpproxy.exe
